travis:
  secure:
    BINSTAR_TOKEN: T6zB6lR0CBjiMEsjw2bNtoi0Y0RTdP27T6+/gyQhAnnp/O/a5pVTcn7fZUIGRqO1EmO6JDPuPmn0HiEqaaC/Mrj8/6QCu/PWD8Fh1XYpYx3gD7L+3fLlelpjsztycnUwlzdRYP/lApiRIezbB1m8O/MS/JeqyFrsMaCmJghDNjplUwhQpXiSIHl1gcPvRMNyTcYlpujt4a1xFCiKUk0dGRgz350OmBVyvJnjoY3O5H6UJDoaWF3VZK5E9dYpCDS0XedjWfD1DfpyxZtI9Wyf7B8NNN9IIhmI6a0wuVF1ykqFxNKd0xkxJPF1YJ5EeKAjDzK+Hi+JrSmxwJZtFTbEky5f45rO6sKEE6IMt8j8GR0to7TlN+x+agGM8Xyn7OhDp/Wcx9Bj4eqWOTHG3N4gc1fMnUOJkWRee/yCu5zO2E/E5gzxjgfli8rFhGD7rqKZKgXz7DJH52h9ObxZ61AXf3lOmmNh39ih1Tw/qk13QJYOZJtPieaWJVlUbR6kzrMkgt3/gmHrg1l8MQH84h5VqDEwYUvFfN05Uut0M6tCeRKI33gXOWvr+kAxnEmFXNe/lJ32RQT61uPKXX0VG3mFf75TiB0SuWqywYAJmTn1rswTYr+78YlLrn1lce4b+c+cgMgC3odnufe25Grgww3UoMH7sgJDlVkA9txg8LUs7mY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
